spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver

#mybatis-plus:
#  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
#  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.lyp_mybatisplus.entity




